### ISSUE TITLE
Split webpack configurations

### ISSUE THREAD

**Issue by 0x241F31** [high1/solid-typescript-starter#1]
Hey!
I think splitting configuration for production and development would make config file more readable. I can create a pr. What do you think?

**Comment by high1** [comment]
It definitely would. Feel free to do it, of course.

**Comment by high1** [comment]
I've updated the boilerplate, and switched to webpack 5 - and in the process, removed typescript configuration for webpack, as the plugins are still catching up with the new, integrated definitions. This should be relatively easy to do now.

**Comment by high1** [comment]
This was done in 9343cec763a9b237aeb8ecf4bd55fc30ed84b470.
