### ISSUE TITLE
How did you generate the *.d.ts file

### ISSUE THREAD

**Issue by danielfliegauf** [high1/solid-typescript-starter#2]
Hey High1,

could you maybe explain, how you generated the `App.css.d.ts` File and how it would work for new Coponents?
As far as I understand you need something like `dts-css-modules-loader` ...

Thank you!
Daniel

**Comment by high1** [comment]
It was manually written, you don't need a loader for simple typescript definitions...

**Comment by danielfliegauf** [comment]
Hey High1,

thanks for the fast answer. This sounds fair sofar. I have one more question though: 
If I change one class e.g. `.AppHeader` to `.AppHeaderNew` and also the according d.ts file then Webpack will throw the following error : `Property 'AppHeaderNew' does not exist on type 'typeof import("/solid-typescript-starter/src/components/App.css")'`. 

Once I restart Webpack everything is ok. 
Can you reproduce this also on your side? And if yes, do you know any advice to fix this?

I tried now for quite some time but I cannot figure it out -.- I would really appreciate any hint :)

**Comment by high1** [comment]
Sorry for the long wait, I forgot to reply... I need to check the transpiling process, Babel is used for stripping types and solid, and another process - ForkTsCheckerWebpackPlugin - checks types in another thread.

**Comment by high1** [comment]
Regards, I've copied type definitions for .module.css from Next.js - this is not strong, but I think good enough - removes the burden of adding extra css definitions for modules from the developer. Development now uses css-loader to load css files, along with post-css, so you can rename classes during development.
